In [1]:
import numpy as np

In [2]:
s = 2
v = np.array([3, 6])
s+v

array([5, 8])

# Transpose

In [3]:
A = np.array([[1, 2, 3], [4, 5, 6]])

print("A =\n", A)
print("A^T =\n", A.T)

A =
 [[1 2 3]
 [4 5 6]]
A^T =
 [[1 4]
 [2 5]
 [3 6]]


### 1. Row vs Column vectors (data organization)
Imagine you record truck speeds at 3 times>
u = (60, 62, 59)

In [4]:
u = np.array([60, 62, 59])
print(u)
print()
print(u.T.shape)
print(u.T)

[60 62 59]

(3,)
[60 62 59]


### 2. Dot product with transpose
If u and v are column vectors

In [5]:
u = np.array([2, 3, 1])
v = np.array([4, -1, 2])

transpose = sum(u.T * v)
print(transpose)

7


### Sensor data in a workshop

In [6]:
A = np.array([[70, 30, 0.4], [72, 29, 0.5], [68, 31, 0.3], [71, 32, 0.6]])
print(A)

[[70.  30.   0.4]
 [72.  29.   0.5]
 [68.  31.   0.3]
 [71.  32.   0.6]]


In [7]:
A.T

array([[70. , 72. , 68. , 71. ],
       [30. , 29. , 31. , 32. ],
       [ 0.4,  0.5,  0.3,  0.6]])

### Distributive property of dot product

In [8]:
u = np.array([2, 3])
v = np.array([1, 4])
w = np.array([5, -1])


lhs = np.dot(u, v + w)
rhs = np.dot(u, v) + np.dot(u, w)

print("LHS:", lhs)
print("RHS:", rhs)
print("Equal?", np.isclose(lhs, rhs))

LHS: 21
RHS: 21
Equal? True


In [9]:
u = np.array([3,4])
v = np.array([1, 2])
w = np.array([2, -1])
c = 2

print("Commutative:", np.dot(u, v), np.dot(v, u))
print("Distributive: ", np.dot(u, v+w), np.dot(u, v) + np.dot(u, w))
print("Scalar associativity: ", np.dot(c*u, v), c*np.dot(u, v))
print("Zero vector: ", np.dot(u, np.zeros_like(u)))
print("Self-dot = || u ||^2 ", np.dot(u,u), np.linalg.norm(u)**2)

Commutative: 11 11
Distributive:  13 13
Scalar associativity:  22 22
Zero vector:  0
Self-dot = || u ||^2  25 25.0


In [10]:
import math
theta_rad = np.arccos(-10/math.sqrt(221))
theta_deg = np.degrees(theta_rad)
theta_deg

np.float64(132.27368900609375)

In [11]:
15/4

3.75

### Vector basics

In [12]:
u = np.array([3, -1])
v = np.array([2, 4])

uv = u + v
umv = u - v

print("u+v = ", uv)
print("u-v = ", umv)

u+v =  [5 3]
u-v =  [ 1 -5]


### Magnitude & unit vectors

In [13]:
u = np.array([6, 2, -3])

mag = np.linalg.norm(u)
unit = u/mag

print("Magnitude = ", mag)
print("Unite Vectors =", unit)

Magnitude =  7.0
Unite Vectors = [ 0.85714286  0.28571429 -0.42857143]


### Dot product

In [14]:
u = np.array([2, 3])
v = np.array([1, -4])

dot = np.dot(u, v)
theta = np.arccos(dot/(np.linalg.norm(u)*np.linalg.norm(v)))
print("Dot: ", dot)
print("Angle (deg): ", np.degrees(theta))

Dot:  -10
Angle (deg):  132.27368900609375


### Dot product properties

In [15]:
u = np.array([1, 2])
v = np.array([3, 4])
w = np.array([5, -1])
c = 2

# Commutativity
com = u*v
comv = v*u

print("u*v = v * u = ", com, comv) 

# Distributivity
dis = np.dot(u, (v+w))
dis2 = np.dot(u, v) + np.dot(u, w)
print("u * (v + w) = u * v + u * w -> ", dis, dis2) 

# Scalar associativity
scalar = (c*u)*v
scalar2 = c*(u*v)
print("(cu) * v = c (u*v)", scalar, scalar2)

# self dot u * u = || u || 
uu = np.dot(u, u)
print("u * u = ", uu)

unorm = (np.linalg.norm(u))**2
print("|| u || = ", unorm)

u*v = v * u =  [3 8] [3 8]
u * (v + w) = u * v + u * w ->  14 14
(cu) * v = c (u*v) [ 6 16] [ 6 16]
u * u =  5
|| u || =  5.000000000000001


### Projection

In [16]:
u = np.array([3, 4])
v = np.array([5, 0])

scalar_proj = np.dot(u, v) / np.linalg.norm(v)
vector_proj = (np.dot(u, v) / np.dot(v, v)) *v

print("Scalar proj: ", scalar_proj)
print("Vector proj: ", vector_proj)

Scalar proj:  3.0
Vector proj:  [3. 0.]


### Transpose

In [17]:
A = np.array([[1,2,3], [4,5,6]])
print("A^T:\n", A.T)

A^T:
 [[1 4]
 [2 5]
 [3 6]]


### Broadcasting

In [18]:
A = np.array([[1, 2, 3], [4, 5, 6]])
b = np.array([10, 20, 30])

print("A+b:\n", A+b)

A+b:
 [[11 22 33]
 [14 25 36]]


### Hadamard product

In [19]:
A = np.array([[1, 2], [3,4]])
B = np.array([[5, 6], [7, 8]])
print("Hadamard:\n", A*B)
print("np.dot():\n", np.dot(A, B))
print("@:\n", A@B)

Hadamard:
 [[ 5 12]
 [21 32]]
np.dot():
 [[19 22]
 [43 50]]
@:
 [[19 22]
 [43 50]]


### Outer product

In [20]:
u = np.array([1, 2])
v = np.array([3, 4, 5])

print("Outer product:\n", np.outer(u,v))

Outer product:
 [[ 3  4  5]
 [ 6  8 10]]


### Orthogonal vector decomposition

In [22]:
u = np.array([3, 4])
v = np.array([4, 0])

u_parallel = (np.dot(u, v)/np.dot(u, v))*v
u_perp = u - u_parallel

print("u_parallel: ", u_parallel)
print("u_perp:", u_perp)
print("Check orthogonal:", np.dot(u_parallel, u_perp))

u_parallel:  [4. 0.]
u_perp: [-1.  4.]
Check orthogonal: -4.0
