In [1]:
import numpy as np

In [2]:
s = 2
v = np.array([3, 6])
s+v

array([5, 8])

# Transpose

In [3]:
A = np.array([[1, 2, 3], [4, 5, 6]])

print("A =\n", A)
print("A^T =\n", A.T)

A =
 [[1 2 3]
 [4 5 6]]
A^T =
 [[1 4]
 [2 5]
 [3 6]]


### 1. Row vs Column vectors (data organization)
Imagine you record truck speeds at 3 times>
u = (60, 62, 59)

In [6]:
u = np.array([60, 62, 59])
print(u)
print()
print(u.T.shape)
print(u.T)

[60 62 59]

(3,)
[60 62 59]


### 2. Dot product with transpose
If u and v are column vectors

In [11]:
u = np.array([2, 3, 1])
v = np.array([4, -1, 2])

transpose = sum(u.T * v)
print(transpose)

7


### Sensor data in a workshop

In [12]:
A = np.array([[70, 30, 0.4], [72, 29, 0.5], [68, 31, 0.3], [71, 32, 0.6]])
print(A)

[[70.  30.   0.4]
 [72.  29.   0.5]
 [68.  31.   0.3]
 [71.  32.   0.6]]


In [13]:
A.T

array([[70. , 72. , 68. , 71. ],
       [30. , 29. , 31. , 32. ],
       [ 0.4,  0.5,  0.3,  0.6]])