In [1]:
import numpy as np
import math as mt

### Excercise 2-2
Write an algorithm that computes the norm of a vector by translating equation 2-7
into code. Confirm, using random vectors with different dimensionalities and orientations
that you get the same result as np.linalg.norm(). This excercise is designed to give
you more experience with indexing numpy arrays and translating formulas into code;
in practice, it's often easier to use np.linalg.norm

In [19]:
def norm(u):
    value = 0
    response = 0
    for i in range(u.size):
        value += (u[i])**2
    response = mt.sqrt(value)
    return response

def norm2(u):
    return np.sqrt(np.sum(u**2))

u = np.array([12, -9, 15])
nor = norm(u)
print(nor)
print(np.linalg.norm(u))
print(norm2(u))

21.213203435596427
21.213203435596427
21.213203435596427


In [20]:
np.size?

Signature:       np.size(a, axis=None)
Call signature:  np.size(*args, **kwargs)
Type:            _ArrayFunctionDispatcher
String form:     <function size at 0x0000022CF2182F20>
File:            c:\users\cqti\anaconda3\lib\site-packages\numpy\_core\fromnumeric.py
Docstring:      
Return the number of elements along a given axis.

Parameters
----------
a : array_like
    Input data.
axis : int, optional
    Axis along which the elements are counted.  By default, give
    the total number of elements.

Returns
-------
element_count : int
    Number of elements along the specified axis.

See Also
--------
shape : dimensions of array
ndarray.shape : dimensions of array
ndarray.size : number of elements in array

Examples
--------
>>> import numpy as np
>>> a = np.array([[1,2,3],[4,5,6]])
>>> np.size(a)
6
>>> np.size(a,1)
3
>>> np.size(a,0)
2
Class docstring:
Class to wrap functions with checks for __array_function__ overrides.

All arguments are required, and can only be passed by position

### Excercise 2-3
Create a python function that will take a vector as input and output a unit vector in the same direction. What happens when you input the zeros vector?

In [28]:
def unitvector(u):
    norm = np.linalg.norm(u)
    if norm == 0:
        raise ValueError("Zero vector has no direction, so it has no unit vector")
    return u / norm


u = np.array([3, 4])

print(unitvector(u))
print(unitvector([0, 0]))

[0.6 0.8]


ValueError: Zero vector has no direction, so it has no unit vector

### Excercise 2-4
You know how to create unit vectors; what if you want to create a vector of any arbitrary magnitude? Write a python function that will take a vector
and a desired magnitude as inputs and will return a vector in the same direction but with a magnitude corresponding to the second input.

In [1]:
import numpy as np

def set_magnitude(v, mag, eps=1e-12):
    norm = np.linalg.norm(v)
    if norm < eps:
        raise ValueError("Zero vector has no direction, cannot rescale")
    return (v/norm) * mag

u = np.array([3, 4])
v10 = set_magnitude(u, 10)
print("New vector: ", v10)
print("Magnitude: ", np.linalg.norm(v10))

New vector:  [6. 8.]
Magnitude:  10.0


In [2]:
u = np.array([1, 1, 1])
rescale = set_magnitude(u, 7)
print("1. Rescale: \n", rescale)

1. Rescale: 
 [4.04145188 4.04145188 4.04145188]


In [4]:
u = np.array([-2, 5])
rescaling = set_magnitude(u, 3)
print("2. Rescaling:\n", rescaling) 

2. Rescaling:
 [-1.11417203  2.78543007]


In [5]:
u = np.array([0, 0, 0])
zeros = set_magnitude(u)
print(zeros)

TypeError: set_magnitude() missing 1 required positional argument: 'mag'

### Exercise 2-5
Write a for loop to transpose a row vector into a column vector with out using a built-in function or method suach as np.transpose() or v.T. This exercise will help you create and index orientation-endowed vectors

In [6]:
u = np.array([1,2,3])
print(u)

[1 2 3]


In [7]:
u.T

array([1, 2, 3])

In [8]:
def row_to_col(row):
    # ensure row is 1D
    row = np.array(row)
    n = row.shape[0]
    print("n = row.shape[0]: ", row.shape[0])

    # create empty column vector
    col = np.zeros((n,1))
    print("col = np.zeros((n+1)): ", np.zeros((n+1)))

    # fill it using a for loop
    for i in range(n):
        col[i, 0] = row[i]

    return col


# example
row_vec = [1, 2, 3, 4]
col_vec = row_to_col(row_vec)

print("Row vector:", row_vec)
print("Column vector:\n", col_vec)

n = row.shape[0]:  4
col = np.zeros((n+1)):  [0. 0. 0. 0. 0.]
Row vector: [1, 2, 3, 4]
Column vector:
 [[1.]
 [2.]
 [3.]
 [4.]]


In [11]:
row = np.array([1,2,3])
print(row)
col = row.reshape(-1, 1)
print(col)
col = np.array([[1, 2, 3]]).T
print(col)

[1 2 3]
[[1]
 [2]
 [3]]
[[1]
 [2]
 [3]]


In [16]:
# Feature vector vs dataset
person = np.array([25, 175, 70])
print("Shape: ", person.shape)
print(person)

Shape:  (3,)
[ 25 175  70]


In [15]:
#As a row (1 sample, 3 features)
row = person.reshape(1, -1)
print("Row shape:", row.shape) 
print(row)

Row shape: (1, 3)
[[ 25 175  70]]


In [17]:
# As a column (3 samples, 1 feature each)
col = person.reshape(-1, 1)
print("Col shape:", col.shape)
print(col)


Col shape: (3, 1)
[[ 25]
 [175]
 [ 70]]


In [19]:
# Let's compute BMI (Body Mass Index) as a linear model:
# BMI = w * x
x = np.array([25, 175, 70])
w = np.array([0, 0.01, 0.1])

# dot product (vector form)
bmi1 = np.dot(w, x)

# Matrxi multiplication (requires row vs col awareness)
bmi2 = w.reshape(1, -1) @ x.reshape(-1, 1)
bmi3 = x * w
bmi4 = x @ w

print("Dot product:", bmi1)
print("Matrix mult:", bmi2)
print(bmi3)
print(bmi4)

Dot product: 8.75
Matrix mult: [[8.75]]
[0.   1.75 7.  ]
8.75


In [21]:
# Transpose in real data
# Say you have sales over 3 months for 2 stores

sales = np.array([[100, 200, 150], [80, 120, 100]])
print("Shape: ", sales.shape)
print(sales)

Shape:  (2, 3)
[[100 200 150]
 [ 80 120 100]]


In [24]:
sales_T = sales.T
print("Shape: ", sales_T.shape)
print(sales_T)

Shape:  (3, 2)
[[100  80]
 [200 120]
 [150 100]]
