In [1]:
import numpy as np

In [5]:
asList = [1,2,3]
asArray = np.array([1,2,3])
rowVec = np.array([[1,2,3]])
colvec = np.array([[1], [2], [3]])

print(f'asList: {np.shape(asList)}')
print(f'asArray: {asArray.shape}')
print(f'rowVec: {rowVec.shape}')
print(f'colVec: {colvec.shape}')
                          

asList: (3,)
asArray: (3,)
rowVec: (1, 3)
colVec: (3, 1)


### Adding two vectors

In [9]:
v = np.array([4, 5, 6])
w = np.array([10, 20, 30])
u = np.array([0, 3, 6, 9])
vPluW = v+w
print(vPluW)
uPlusW = u+w # error! dimensions mismatched!

[14 25 36]


ValueError: operands could not be broadcast together with shapes (4,) (3,) 

In [13]:
v = np.array([4, 5, 6])
w = np.array([[10, 20, 30]]).T

print(v)
print(w)
v+w


[4 5 6]
[[10]
 [20]
 [30]]


array([[14, 15, 16],
       [24, 25, 26],
       [34, 35, 36]])

### Orientationless 1D vector

In [14]:
asArray = np.array([1,2,3])
print(asArray.shape)

# Row vector
rowVec = np.array([[1,2,3]])
print(rowVec.shape)

# Column vector
colVec = np.array([[1], [2], [3]])
print(colVec.shape)

(3,)
(1, 3)
(3, 1)


In [15]:
v = np.array([4, 5, 6])
w = np.array([10, 20, 30])

vPlusW = v + w
print(vPlusW)

[14 25 36]


### Vector subtraction

In [18]:
u = np.array([4, 5, 6])
v = np.array([10, 20, 30])

uMinusV = u - v
print(uMinusV)

[ -6 -15 -24]


### Broadcasting kicks in

In [26]:
u = np.array([4, 5, 6])
v = np.array([[10, 20, 30]]).T

print(u)
print("\n")
print(np.array([[10, 20, 30]]))
print("\n")
print(v)
print("\n")
print("Shapes: ", u.shape, v.shape)
print(u+v)

[4 5 6]


[[10 20 30]]


[[10]
 [20]
 [30]]


Shapes:  (3,) (3, 1)
[[14 15 16]
 [24 25 26]
 [34 35 36]]


### Practice 1

In [27]:
u = np.array([3, -1, 2])
v = np.array([5, 4, -3])

uPlusV = u + v
uMinusV = u - v

print("u + v = ", uPlusV)
print("u - v = ", uMinusV)

u + v =  [ 8  3 -1]
u - v =  [-2 -5  5]


### Practice round 2

In [28]:
 import math
math.sqrt(49)

7.0

In [32]:
w = np.array([6, 2, -3])
mag = np.linalg.norm(w)
unit = w / mag

print("w = ", w)
print("mag = ", mag)
print("unit = ", unit)


w =  [ 6  2 -3]
mag =  7.0
unit =  [ 0.85714286  0.28571429 -0.42857143]
